[2022-02-24 20:01:52,364] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: Sample_one.process_kmeans manual__2022-02-24T20:01:49.740879+00:00 [queued]>
[2022-02-24 20:01:52,377] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: Sample_one.process_kmeans manual__2022-02-24T20:01:49.740879+00:00 [queued]>
[2022-02-24 20:01:52,378] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-24 20:01:52,378] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-24 20:01:52,378] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-24 20:01:52,392] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): process_kmeans> on 2022-02-24 20:01:49.740879+00:00
[2022-02-24 20:01:52,400] {standard_task_runner.py:52} INFO - Started process 92 to run task
[2022-02-24 20:01:52,410] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Sample_one', 'process_kmeans', 'manual__2022-02-24T20:01:49.740879+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpghgg8l1a', '--error-file', '/tmp/tmpf3r56x4w']
[2022-02-24 20:01:52,413] {standard_task_runner.py:77} INFO - Job 42: Subtask process_kmeans
[2022-02-24 20:01:52,496] {logging_mixin.py:109} INFO - Running <TaskInstance: Sample_one.process_kmeans manual__2022-02-24T20:01:49.740879+00:00 [running]> on host 99813ca71bd1
[2022-02-24 20:01:52,576] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=vathana
AIRFLOW_CTX_DAG_ID=Sample_one
AIRFLOW_CTX_TASK_ID=process_kmeans
AIRFLOW_CTX_EXECUTION_DATE=2022-02-24T20:01:49.740879+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-24T20:01:49.740879+00:00
[2022-02-24 20:01:52,925] {dag.py:27} WARNING - Downgrading core protocol version from 66 to 65 for 3844b209-e6f1-4eda-8605-b019293c1e08-us-east1.db.astra.datastax.com:29042:33c650af-8c56-4bb3-9716-13c8a515600f. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2022-02-24 20:01:53,066] {dag.py:27} WARNING - Downgrading core protocol version from 65 to 5 for 3844b209-e6f1-4eda-8605-b019293c1e08-us-east1.db.astra.datastax.com:29042:33c650af-8c56-4bb3-9716-13c8a515600f. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2022-02-24 20:01:53,202] {libevreactor.py:370} ERROR - Closing connection <LibevConnection(140639044044880) 3844b209-e6f1-4eda-8605-b019293c1e08-us-east1.db.astra.datastax.com:29042:33c650af-8c56-4bb3-9716-13c8a515600f> due to protocol error: Error from server: code=000a [Protocol error] message="Beta version of the protocol used (5/v5-beta), but USE_BETA flag is unset"
[2022-02-24 20:01:53,208] {dag.py:27} WARNING - Downgrading core protocol version from 5 to 4 for 3844b209-e6f1-4eda-8605-b019293c1e08-us-east1.db.astra.datastax.com:29042:33c650af-8c56-4bb3-9716-13c8a515600f. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2022-02-24 20:01:53,540] {policies.py:292} INFO - Using datacenter 'us-east1' for DCAwareRoundRobinPolicy (via host '3844b209-e6f1-4eda-8605-b019293c1e08-us-east1.db.astra.datastax.com:29042:33c650af-8c56-4bb3-9716-13c8a515600f'); if incorrect, please specify a local_dc to the constructor, or limit contact points to local cluster nodes
[2022-02-24 20:01:59,302] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 67, in kmeans
    session.close()
AttributeError: 'Session' object has no attribute 'close'
[2022-02-24 20:01:59,340] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=Sample_one, task_id=process_kmeans, execution_date=20220224T200149, start_date=20220224T200152, end_date=20220224T200159
[2022-02-24 20:01:59,386] {standard_task_runner.py:92} ERROR - Failed to execute job 42 for task process_kmeans
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 67, in kmeans
    session.close()
AttributeError: 'Session' object has no attribute 'close'
[2022-02-24 20:01:59,493] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-02-24 20:01:59,583] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
